=== nt-nam/turn-base-rpg/content/schemas/currencies.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "currencies file",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "icon": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "name",
      "description",
      "icon"
    ],
    "additionalProperties": false
  }
}

=== nt-nam/turn-base-rpg/content/currencies/currencies.json
[
  {
    "id": "currency.gold",
    "name": "currency.gold.name",
    "description": "currency.gold.description",
    "icon": "icon:currency/gold"
  },
  {
    "id": "currency.gem",
    "name": "currency.gem.name",
    "description": "currency.gem.description",
    "icon": "icon:currency/gem"
  },
  {
    "id": "currency.energy",
    "name": "currency.energy.name",
    "description": "currency.energy.description",
    "icon": "icon:currency/energy"
  },
  {
    "id": "currency.guild_token",
    "name": "currency.guild_token.name",
    "description": "currency.guild_token.description",
    "icon": "icon:currency/guild_token"
  },
  {
    "id": "currency.event_token",
    "name": "currency.event_token.name",
    "description": "currency.event_token.description",
    "icon": "icon:currency/event_token"
  }
]
